### ISSUE TITLE
Dump function not working on 5.0.d

### ISSUE THREAD

**Issue by douglascrp** [share-extras/js-console#57]
It doesn't matter which object I use, I always get this errors when I use the dump function:

```
500 Internal Error
Stacktrace-Details:
org.springframework.extensions.webscripts.WebScriptException: 07250002 Wrapped Exception (with status template): 07250022 Failed to execute script 'Javascript Console Script': null
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1127)
	at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:476)
	at de.fme.jsconsole.ExecuteWebscript.access$100(ExecuteWebscript.java:71)
	at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:357)
	at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:351)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
	at de.fme.jsconsole.ExecuteWebscript.runWithTransactionIfNeeded(ExecuteWebscript.java:350)
	at de.fme.jsconsole.ExecuteWebscript.access$000(ExecuteWebscript.java:71)
	at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:328)
	at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:326)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at de.fme.jsconsole.ExecuteWebscript.runScriptWithTransactionAndAuthentication(ExecuteWebscript.java:326)
	at de.fme.jsconsole.ExecuteWebscript.execute(ExecuteWebscript.java:199)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:437)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.scripts.ScriptException: 07250022 Failed to execute script 'Javascript Console Script': null
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:204)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:212)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:174)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:102)
	at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:422)
	... 42 more
Caused by: java.lang.NullPointerException
	at de.fme.jsconsole.JavascriptConsoleScriptObject.dumpObject(JavascriptConsoleScriptObject.java:316)
	at de.fme.jsconsole.JavascriptConsoleScriptObject.addDump(JavascriptConsoleScriptObject.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20._c_dump_2(Javascript Console Script:7)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20.call(Javascript Console Script)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20._c_script_0(Javascript Console Script:8)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20.call(Javascript Console Script)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20.call(Javascript Console Script)
	at org.mozilla.javascript.gen.Javascript_Console_Script_20.exec(Javascript Console Script)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:502)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:200)
	... 46 more


An error inside the HTTP server which prevented it from fulfilling the request.
undefined
```

Alfresco 5.0.d
Oracle Java 1.8.0_60-b27
Ubuntu 14.04
Tomcat 7.0.63

**Comment by shazada** [comment]
I have the same issue

**Comment by jgoldhammer** [comment]
I will work on it the next days...

**Comment by jgoldhammer** [comment]
Fixed with Lukasz Pull Request.
Thanks
