### ISSUE TITLE
Error when trying to dump the auditing information from repository in Alfresco 5.2

### ISSUE THREAD

**Issue by douglascrp** [share-extras/js-console#78]
When performing some batch processing in an Alfresco 5.2.e server, I got the following error:

```
500 Internal Error
Stacktrace-Details:
org.springframework.extensions.webscripts.WebScriptException: 08120010 Wrapped Exception (with status template): maxResults must be greater than 0
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
	at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:405)
	at de.fme.jsconsole.ExecuteWebscript.access$100(ExecuteWebscript.java:56)
	at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:280)
	at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:273)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:352)
	at de.fme.jsconsole.ExecuteWebscript.runWithTransactionIfNeeded(ExecuteWebscript.java:272)
	at de.fme.jsconsole.ExecuteWebscript.access$000(ExecuteWebscript.java:56)
	at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:250)
	at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:247)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at de.fme.jsconsole.ExecuteWebscript.runScriptWithTransactionAndAuthentication(ExecuteWebscript.java:247)
	at de.fme.jsconsole.ExecuteWebscript.execute(ExecuteWebscript.java:121)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:467)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: maxResults must be greater than 0
	at org.alfresco.repo.domain.audit.ibatis.AuditDAOImpl.findAuditEntries(AuditDAOImpl.java:316)
	at org.alfresco.repo.domain.audit.AbstractAuditDAOImpl.findAuditEntries(AbstractAuditDAOImpl.java:466)
	at org.alfresco.repo.audit.AuditComponentImpl.auditQuery(AuditComponentImpl.java:1030)
	at org.alfresco.repo.audit.AuditServiceImpl.auditQuery(AuditServiceImpl.java:159)
	at sun.reflect.GeneratedMethodAccessor1001.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy129.auditQuery(Unknown Source)
	at de.fme.jsconsole.DumpService.getAudits(DumpService.java:490)
	at de.fme.jsconsole.DumpService.dumpObject(DumpService.java:179)
	at de.fme.jsconsole.DumpService.addDump(DumpService.java:128)
	at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:354)
	... 43 more


An error inside the HTTP server which prevented it from fulfilling the request.
maxResults must be greater than 0
```

This seems to be related with the change described in the following issue https://issues.alfresco.com/jira/browse/ACE-5591

I am trying to fix it by simply commenting the line https://github.com/share-extras/js-console/blob/master/javascript-console-repo/src/main/java/de/fme/jsconsole/DumpService.java#L179 as this is the one responsible to generate the executing with the -1 parameter, which is, as the exception states, illegal now.
https://github.com/Alfresco/community-edition-old/blob/master/projects/repository/source/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java#L316

Let me know if anyone has something agains the removal of that audit call.

**Comment by douglascrp** [comment]
Another option, that I believe is better, is change the limit value for 100, instead of the current -1 (https://github.com/share-extras/js-console/blob/master/javascript-console-repo/src/main/java/de/fme/jsconsole/DumpService.java#L488)

As the mentioned jira issue states, that is the new default value.

**Comment by jgoldhammer** [comment]
Merged. Thanks for the bug report.
